### ISSUE TITLE
Making improvements to reliability of track downloads.

### ISSUE THREAD

**Issue by alexmercerind** [raitonoberu/harmonoid-service#14]
We all know that the server currently has many problems regarding downloading of music. In other words, it is very unstable in downloading music. e.g.:
- Whenever newer version of YouTube-DL releases (i.e. YouTube messes with something again). The track download fails. And there is no way to update YouTube-DL yet other than re-pushing the code to Heroku.
- The error handling is very bad at the moment, one has to see server logs very patiently to see what messed up.
- Sometimes cookies mess up. The track download fails. (@raitonoberu recommended using fresh cookies. And it works.)
  - If you see in the initial version of the server, I wasn't even using cookies. At that time, the downloading failed very often randomly and the reason was Google sending 429 response & captcha to solve (Since, we aren't the only person using YouTube-DL on Heroku servers). Then, at a random subreddit, I found out that using cookies prevents this to an extent. 

I'm so fed up of these randomly occurring problems while downloading my music. So I have made some little improvements to the server (yet to push).

- Now server will check for latest available YouTube-DL version on startup & update it.
  - But wait... What if the new version releases when the server is already started, it will even update if a download fails.
- If a track download fails for some reason, then server will try to clear cookies file & update YouTube-DL & then try to download track again & send updated response.
- The server will now very clearly say "YouTube-DL Failed." when visiting /trackdownload in a browser (if something messes up really bad & even retrying download couldn't fix the problem) & will not try to add metadata to "non existing track file".

**What I did now...**
Here (in the following log), a track failed to download because of older version of YouTube-DL, so the server updated the YouTube-DL & cleared the cookies.txt itself & redownloaded the track to send it.
```
[server] Download request in ID format.
[youtube] Successfully retrieved metadata of track ID: DZzfShAg83A.
[youtube] DZzfShAg83A: Downloading webpage
[youtube] DZzfShAg83A: Downloading embed webpage
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] Track download unsuccessful for track ID: DZzfShAg83A.
[metadata] Skipped adding metadata to track ID: DZzfShAg83A.

[diagnosis] (1/2) Deleting cookies file.
[diagnosis] (2/2) Attempting to update YouTube-DL.
[update] Installed YouTube-DL version: 2020.09.20.
[update] Latest YouTube-DL Version   : 2020.11.01.1.
[update] Updating YouTube-DL...
[update] Updated YouTube-DL.
[diagnosis] Retrying download for track ID: DZzfShAg83A.

[server] Download request in ID format.
[youtube] Successfully retrieved metadata of track ID: DZzfShAg83A.
[youtube] DZzfShAg83A: Downloading webpage
[download] Destination: DZzfShAg83A.m4a
[download] 100% of 3.71MiB in 00:30
[ffmpeg] Correcting container in "DZzfShAg83A.m4a"
[youtube] Track download successful for track ID: DZzfShAg83A.
[metadata] Getting album art: https://lh3.googleusercontent.com/-5tTV-tjK2zIJE2bSglmSCAj68g_6_XdnhwtqxUBC4ZroqPNI-AHO9GAxXFVg4b9IQGJOP42pI1dU7w=w544-h544-l90-rj
[metadata] Album art retrieved.
[metadata] Successfully added metadata to track ID: DZzfShAg83A.
[server] Sending audio binary for track ID: DZzfShAg83A.
```

I haven't made some legendary changes but this will definitely improve handling of the server & one will no longer have to re-push code for minor problems.

**Comment by alexmercerind** [comment]
How about mirroring this repo to BitBucket or something aswell. GitHub is wild nowadays. 😂

**Comment by raitonoberu** [comment]
Hello, @alexmercerind!
You've done a great job. I also had problems downloading tracks, but I didn't have enough time to deal with them.

`If a track download fails for some reason, then server will try to clear cookies file`
I want to ask you one thing: do we really need this cookie file? Does it matter? There are so many problems with it, why don't we just disable it?

`How about mirroring this repo to BitBucket or something aswell?`
No idea. I love GitHub, it is convenient and nice-looking. If you want, make a mirror.

We can also check YT-DL updates in a separate thread (every hour, for example).

Thanks!

**Comment by alexmercerind** [comment]
👋 Hi @raitonoberu,

During the initial days of development, I didn't use cookies in the server but, at that time server used to get 429 status from youtube-dl very frequently causing me to re-push the code a lot.
But using ```--cookies``` in youtube-dl fixes it.

I found about this [here](https://askubuntu.com/questions/1220266/youtube-dl-do-not-working-http-error-429-too-many-requests-how-can-i-solve-this) & [here](https://www.reddit.com/r/youtubedl/comments/ejgy2l/yt_banning_ips_with_http_error_429_too_many/fsymxh7?utm_source=share&utm_medium=web2x&context=3).
Not really sure if this is a thing... 😅

**Comment by alexmercerind** [comment]
I made commit against the master branch (M4A & YouTube Music) & added [some comments](https://github.com/raitonoberu/harmonoid-service/commit/c86d6577c7e48ee4a6b0a314e9b77b917808fc75) along the way. Feel free to criticize & improve. (Not the most efficient programmer 😅)

**Comment by raitonoberu** [comment]
I created a new branch called "master-next", but haven't deployed it yet. It works well on my computer, I'll deploy it in the morning 😴

**Comment by raitonoberu** [comment]
Looks like ffmpeg does something with .m4a:
![image](https://user-images.githubusercontent.com/64320078/97965935-b10ff600-1ded-11eb-8e40-60ffceacf62b.png)
I don't remove it from the server and it works OK. Feel free to merge the branches as soon as you are sure everything is working 🙃
Now it's deployed at https://harmonoid-ru.herokuapp.com/

**Comment by alexmercerind** [comment]
Hi @raitonoberu!

Your implementation is sweet but has few problems. I have deployed your code [here at harmonoid-debug.herokuapp.com](https://harmonoid-debug.herokuapp.com/trackdownload?track_id=DZzfShAg83A) and the **youtube-dl is not being updated properly** causing an 500 status code & internal server error, which even leads to error from mutagen. Second thing to say (I'm not super sure) is that, library imports need to be reloaded (as youtube_dl is being updated) using ```importlib.reload``` (I used sys.modules instead). For example, if current version of youtube_dl (at the time of deploying) is ```a.b.c```, then value of CURRENT_VERSION will be ```a.b.c``` & lets assume, later it got updated to ```x.y.z```. Now the value of CURRENT_VERSION should be updated to ```x.y.z``` for receiving a newer update or for confirming that youtube_dl is already at ```x.y.z``` (but here it will still stay at ```a.b.c```).


**Error log on your server:** (I degraded youtube_dl to 2020.9.20 to test updates)

<details>

```
2020-11-03T09:59:34.435748+00:00 app[web.1]: [server] Download request in ID format.
2020-11-03T09:59:36.013850+00:00 app[web.1]: [youtube] Successfully retrieved metadata of track ID: DZzfShAg83A.
2020-11-03T09:59:38.128920+00:00 heroku[router]: at=info method=GET path="/trackdownload?track_id=DZzfShAg83A" host=harmonoid-debug.herokuapp.com request_id=8b00ebe5-44ad-43fa-8682-cff9968dbf18 fwd="132.154.14.209" dyno=web.1 connect=0ms service=3697ms status=500 bytes=174 protocol=https
2020-11-03T09:59:38.124332+00:00 app[web.1]: [stdout] [youtube] DZzfShAg83A: Downloading webpage
2020-11-03T09:59:38.124342+00:00 app[web.1]: [youtube] Downloading just video DZzfShAg83A because of --no-playlist
2020-11-03T09:59:38.124343+00:00 app[web.1]: [youtube] DZzfShAg83A: Downloading embed webpage
2020-11-03T09:59:38.124344+00:00 app[web.1]:
2020-11-03T09:59:38.124367+00:00 app[web.1]: [stderr] ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2020-11-03T09:59:38.124368+00:00 app[web.1]:
2020-11-03T09:59:38.124372+00:00 app[web.1]: [youtube] Track download successful for track ID: DZzfShAg83A.
2020-11-03T09:59:38.126313+00:00 app[web.1]: 132.154.14.209:0 - "GET /trackdownload?track_id=DZzfShAg83A HTTP/1.1" 500
2020-11-03T09:59:38.131769+00:00 app[web.1]: [2020-11-03 09:59:38 +0000] [13] [ERROR] Exception in ASGI application
2020-11-03T09:59:38.131771+00:00 app[web.1]: Traceback (most recent call last):
2020-11-03T09:59:38.131787+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 391, in run_asgi
2020-11-03T09:59:38.131788+00:00 app[web.1]: result = await app(self.scope, self.receive, self.send)
2020-11-03T09:59:38.131788+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
2020-11-03T09:59:38.131789+00:00 app[web.1]: return await self.app(scope, receive, send)
2020-11-03T09:59:38.131790+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/fastapi/applications.py", line 179, in __call__
2020-11-03T09:59:38.131790+00:00 app[web.1]: await super().__call__(scope, receive, send)
2020-11-03T09:59:38.131791+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
2020-11-03T09:59:38.131791+00:00 app[web.1]: await self.middleware_stack(scope, receive, send)
2020-11-03T09:59:38.131792+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
2020-11-03T09:59:38.131792+00:00 app[web.1]: raise exc from None
2020-11-03T09:59:38.131792+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
2020-11-03T09:59:38.131793+00:00 app[web.1]: await self.app(scope, receive, _send)
2020-11-03T09:59:38.131793+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
2020-11-03T09:59:38.131794+00:00 app[web.1]: raise exc from None
2020-11-03T09:59:38.131794+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
2020-11-03T09:59:38.131794+00:00 app[web.1]: await self.app(scope, receive, sender)
2020-11-03T09:59:38.131795+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
2020-11-03T09:59:38.131795+00:00 app[web.1]: await route.handle(scope, receive, send)
2020-11-03T09:59:38.131795+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
2020-11-03T09:59:38.131796+00:00 app[web.1]: await self.app(scope, receive, send)
2020-11-03T09:59:38.131797+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
2020-11-03T09:59:38.131797+00:00 app[web.1]: response = await func(request)
2020-11-03T09:59:38.131798+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/fastapi/routing.py", line 183, in app
2020-11-03T09:59:38.131798+00:00 app[web.1]: dependant=dependant, values=values, is_coroutine=is_coroutine
2020-11-03T09:59:38.131799+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
2020-11-03T09:59:38.131799+00:00 app[web.1]: return await dependant.call(**values)
2020-11-03T09:59:38.131799+00:00 app[web.1]: File "/app/main.py", line 59, in TrackDownload
2020-11-03T09:59:38.131800+00:00 app[web.1]: return await harmonoidService.TrackDownload(track_id, album_id, track_name)2020-11-03T09:59:38.131800+00:00 app[web.1]: File "/app/harmonoidservice/downloading.py", line 135, in TrackDownload
2020-11-03T09:59:38.131801+00:00 app[web.1]: await self.SaveMetaData(trackInfo)
2020-11-03T09:59:38.131801+00:00 app[web.1]: File "/app/harmonoidservice/downloading.py", line 80, in SaveMetaData
2020-11-03T09:59:38.131801+00:00 app[web.1]: await audioFile.init()
2020-11-03T09:59:38.131802+00:00 app[web.1]: File "/app/harmonoidservice/async_mutagen.py", line 11, in init
2020-11-03T09:59:38.131802+00:00 app[web.1]: await loop.run_in_executor(None, super().__init__, self.filename)
2020-11-03T09:59:38.131802+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/concurrent/futures/thread.py", line 57, in run
2020-11-03T09:59:38.131803+00:00 app[web.1]: result = self.fn(*self.args, **self.kwargs)
2020-11-03T09:59:38.131803+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/mutagen/_file.py", line 48, in __init__
2020-11-03T09:59:38.131804+00:00 app[web.1]: self.load(*args, **kwargs)
2020-11-03T09:59:38.131804+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/mutagen/_util.py", line 155, in wrapper
2020-11-03T09:59:38.131804+00:00 app[web.1]: writable, create) as h:
2020-11-03T09:59:38.131805+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/contextlib.py", line 112, in __enter__
2020-11-03T09:59:38.131805+00:00 app[web.1]: return next(self.gen)
2020-11-03T09:59:38.131805+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/mutagen/_util.py", line 272, in _openfile
2020-11-03T09:59:38.131805+00:00 app[web.1]: raise MutagenError(e)
2020-11-03T09:59:38.131806+00:00 app[web.1]: mutagen.MutagenError: [Errno 2] No such file or directory: 'DZzfShAg83A.m4a'
```
Due to this chain of errors it is unable to show it in HTML response.

</details>

**Error log on my server:** I degraded youtube_dl to 2020.9.20 & set reTry=False for causing error. (Now errors are so hard to produce).

<details>

```
[server] Download request in ID format.
[youtube] Successfully retrieved metadata of track ID: DZzfShAg83A.
[youtube] DZzfShAg83A: Downloading webpage
[youtube] DZzfShAg83A: Downloading embed webpage
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] Track download unsuccessful for track ID: DZzfShAg83A.
[metadata] Skipped adding metadata to track ID: DZzfShAg83A.
[server] Sending status code 500 for track ID: DZzfShAg83A.
```
![Capture](https://user-images.githubusercontent.com/28951144/97974990-6a6ecb80-1dee-11eb-9ff4-67fe1cd27b64.PNG)

</details>

**Comment by alexmercerind** [comment]
My version of server (though written in nasty manner):
-  Skips mutagen if download fails.
-  Updates youtube_dl successfully, even if more than one subsequent versions of youtube_dl are released during the runtime of the app. (Since, version of youtube_dl isn't always constant as the version at the time of deploying). Importing youtube_dl in a functional scope gives the newest ```__version__``` everytime that function is called (not at the version at the time of deploying).
-  It displays the error message (if it occurs, now no errors should exist due to auto-updates) with simple 500 status code from youtube_dl in the HTML (instead of panicking as in the log below).

😃😃😃 I ALSO WANNA SAY THAT THIS ISN'T SOMETHING URGENT... STUDENT LIFE ISN'T EASY. TAKE CARE OF YOUR SCHEDULE & STUDIES (I'm sounding like boomer ik.)

**Comment by raitonoberu** [comment]
Hello @alexmercerind!

Well, the first log contains both `[youtube] Track download successful for track ID: DZzfShAg83A.` and `[stderr] ERROR: Unable to extract JS player URL`. Youtube-dl is a problem: it returns the status code 0 (which means "program completed successfully") **even if this error occurred**. All we can do is search for the word "ERROR" in stderr (I'll try it in the following commits). Do you have any other ideas?

We don't have to re-import YT-DL because of these lines:
https://github.com/raitonoberu/harmonoid-service/blob/af00a77625c2ff21f66109d79328554034c020a0/harmonoidservice/downloading.py#L35-L39
This variable stores the current version. Moreover, the server restarts quite often (due to inactivity, etc.) and the variable upgrades. It should be working well 🤪

What about me... I'm currently on vacation, and after that, distance learning because of Coronavirus will begin (it's much easier than usual). So don't care about this and wear a mask! 😷

Thank you!

**Comment by alexmercerind** [comment]
Hi @raitonoberu & @mytja 😁!

**It seems the perfect time to start working on Harmonoid once again.**

As a sidenote, I have integrated GitHub actions into the master branch of the repository. **Which means that you'll be able to get the latest APK available without waiting for me to compile it** 🎉.

You can check the "Actions" tab of the repository. Latest build is [here](https://github.com/alexmercerind/harmonoid/runs/1357591492). It just has new artists search. BUT DON'T USE IT RIGHT NOW.
<details>

![Screenshot 2020-11-05 155110](https://user-images.githubusercontent.com/28951144/98228582-c49e9680-1f7e-11eb-9b50-13eb2db2f4c9.jpg).

</details>

Saying this, currently app has many problems in its core...
- As initially I wasn't bothering with storage permissions, the app had to save tracks internally making them inaccessible for sharing or to the user. (Which isn't great...)
- The app currently stores track information (if you know) in a separate JSON along with the track (also album art's PNG is stored separately) instead of reading from metadata of a track file. At that time, I couldn't download MP3 from YouTube-DL on Heroku (I was unaware of FFmpeg build-pack) & didn't know any library for reading ID3 tags (ID3 tags aren't on M4A either way), so I hid the downloaded tracks from users & saved in a "wacky" way, because I had no choice. This is also bad for storage. Now that harmonoid-service has MP3 support, we're good to go. 🍀 I'm thinking to use [this](https://pub.dev/packages/dart_tags) for reading tags (I'm not that intelligent to write something for reading metadata myself).
- Since the way is "wacky"... I wrote highly confusing code to squeeze the performance. Now, I'm having trouble to maintain it & add new features.
- Now my plan is to just be like other music apps in terms of functionality & playback (i.e playing music saved in phone's "Music" folder either it is downloaded from Harmonoid. This might even make this app's way to Google's Play Store. 👌 
- After planning this much rewrite to the app, playing "old collection" (the "wacky mess") will be a challenge or I have to just ask users to redownload their collection in the newer version of Harmonoid.




>
>What about me... I'm currently on vacation, and after that, distance learning because of Coronavirus will begin (it's much easier than usual). So don't care about this and wear a mask! 😷
>

It's pretty much same here in India... We got online classes going on for students but, this year I completed my 12th grade (highest school standard in India) education... So I'm on a sort of vacation too. Now after this school education, we apply for higher education, which means that one has to crack an competitive exam called JEE (Joint Entrance Examination) for getting a "Good Government Engineering College" (Yes, I applied for engineering, student of other streams have other exams). Government College is considered better here, because they are cheaper (Government aids the fees) & "have reputation" (in way that only students who studied hard get to study here). If one is unable to crack JEE, he/she can take admission private college & pay the high fees. Fortunately, I got a reputed government college in my state according to my rank with "Electronics & Communication Engineering", now I'll study there. I had Python as a subject from my 10th grade & I'm writing code since then (first language).

I just meant that I don't wanna misguide anyone for writing code on GitHub & avoiding studies 😅, I'm just free nowadays so I'm writing a lot of code 😂. No more long comments.

☮

**Comment by mytja** [comment]
Hi, @alexmercerind and @raitonoberu 

> - Now my plan is to just be like other music apps in terms of functionality & playback (i.e playing music saved in phone's "Music" folder either it is downloaded from Harmonoid. This might even make this app's way to Google's Play Store. 👌  

Awesome!
Just note, that you might have to pay fees to enter the app to Google Play.
Huawei App Store is I think without fees, but you have to submit a Gov. ID.
Meanwhile, Samsung Galaxy Store is fully free, and requires no ID.

> What about me... I'm currently on vacation, and after that, distance learning because of Coronavirus will begin (it's much easier than usual). So don't care about this and wear a mask! 😷

Yeah, it is very weird also in Slovenia.
I like your mask project, @raitonoberu 
Hope it will get better 😔

**Comment by raitonoberu** [comment]
Nice to meet you guys again! I hope you're all right.

I think that Google Play and other app stores are not intended for Harmonoid. Even if the app is not kind of piracy... how do we explain to the average user how to deploy the server? [F-Droid](https://f-droid.org/) can be our solution, there are far fewer normies here🙂

My mask project was completed in a few hours (80% of the time I was solving problems with converting to .exe). Here's the story: my classmates participated in a kind of competition, and their last task was to create such an application. None of them were interested in programming, so they decided to call me. I went to school and the teacher said that the project should be completed... the next morning 😯. And I did, the first commit was made at 2am :) Now I don't know if we won or not, but the teachers are thrilled and my comrades and I will eat cake.

Don't be afraid to write long comments, I'm really interested to know more about you 😄
Agree, comments on Github are not suitable for casual communication. What if we create an open Discord server for Harmonoid with separate text channels?

Peace.

**Comment by alexmercerind** [comment]
Yeah, we cannot explain how to deploy a server to a random guy, so the plan is to just publish this app as "A generic music player" with "hidden harmonoid features" 😉😝.

Haha... Yeah, my classmates are same, apparently very few people are interested in programming & I'm very happy to find two friends here on GitHub who actually enjoy writing code. 😂
I can imagine the face of your teachers when you showed your project to them. It is really well made, everything from UI to functionality. What a savage moment. 🤣
I have never used OpenCV or machine learning yet. So I was also impressed with that. You've made it really good.

Yeah.. Idea of discord is really great... but I have never used it "like a pro"... so I don't know much about server etc. I have to see or you can make your own & give the invite link. 😁
